initial = read.table("data/electricity.txt",header=TRUE,sep=";",stringsAsFactors=FALSE)
initial$Date <- as.Dates(initial$Date,"%d/%m/%Y")
data<-initial[which(initial$Dates=="2007-02-01" | initial$Dates=="2007-02-02"),]
times <- as.POSIXct(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
quartz()
par(mar=c(4.5,4.5,2,2))
plot(times,data$Sub_metering_1,type='l',ylab="Energy sub metering",xlab="")
lines(times,data$Sub_metering_2,col="red")
lines(times,data$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"))
dev.copy(png,file="plot3.png")
dev.off()